### ISSUE TITLE
How do I get the skeleton coordinates of the model

### ISSUE THREAD

**Issue by Luckyalum** [QianliM/cape_utils#2]
How do I get the skeleton coordinates of the model, which I don't see in the data set. 
Thank you.

**Comment by qianlim** [comment]
Hi, if you are referring to joint locations, you can use the SMPL model to get them from the undressed bodies (provided in the dataset). Specifically, download the [SMPL model](https://smpl.is.tue.mpg.de/), and use the SMPLX python package to load the SMPL model easily. See the README there for how to use the package load the SMPL model. 

When you load the model using the [create function](https://github.com/vchoutas/smplx/blob/ec3ce094d0a6db8d8635c1c8b4b26427763e15f2/smplx/body_models.py#L2271) or directly call the [model constructor](https://github.com/vchoutas/smplx/blob/c63c02b478c5c6f696491ed9167e3af6b08d89b1/smplx/body_models.py#L106), pass the vertices of the subject's undressed body to the `v_template` arg. This way you load the personal body shape template of this subject. Then you can simply bring the model to any pose, and get the joint location under that pose. See [this example code](https://github.com/vchoutas/smplx/blob/ec3ce094d0a6db8d8635c1c8b4b26427763e15f2/examples/demo.py#L55) for details.

**Comment by Luckyalum** [comment]
I solved the problem in your way, thank you.
