### ISSUE TITLE
About the shape parameters of each subject

### ISSUE THREAD

**Issue by HongwenZhang** [QianliM/cape_utils#5]
Hi, thanks for your contributions to this dataset!

When I process the CAPE .npz files, I can only find the corresponding pose parameters of each subject. The shape information seems to be provided implicitly in `minimal_body_shape` as the form of vertices. Could the shape parameters be shared and included in the .npz files? 

Best regards!

**Comment by qianlim** [comment]
Hi, it's true that the shape information is provided by each subject's minimally-clothed v_template. Unfortunately during registration we did not save the betas of each subject. However if you need them, you can easily try to compute them on your own: load a gender-specific SMPL model, keep the pose parameters to be 0 (in T-pose) and optimize the betas such that the model and the provided minimal v_template match.

**Comment by HongwenZhang** [comment]
Thanks for your response! I will try optimizing the betas by fitting the vertices in T-pose.

**Comment by ShenhanQian** [comment]
Hi Qianli, thanks for this dataset.

I have tried fitting the shape parameter `beta` with the L1 loss and the Adam optimizer but found it hard to precisely reconstruct the provided T-pose vertices for a subject. The reconstruction loss converges at around 1.3e-3, and the shape of the head, wrists and foot look quite different.

The given minimal body shape for subject 00096:
<img width="1661" alt="given" src="https://user-images.githubusercontent.com/23174052/147456556-90584efa-4437-474e-98c7-ec279234756f.png">

The fitted body shape:
<img width="1661" alt="fitted" src="https://user-images.githubusercontent.com/23174052/147456564-cb1d1048-220d-410d-baed-579da4f1c226.png">

I am using the SMPL body model from [VPoser](https://github.com/nghorbani/human_body_prior) with the latest components `basicmodel_m_lbs_10_207_0_v1.1.0.pkl` and `basicmodel_m_lbs_10_207_0_v1.1.0.pkl` with `num_beta=300`.

Is this is abnormal? would you please leave me some advice to address this? Thank you!
