### ISSUE TITLE
The order of the points for minimal shape and clothed shape is inconsistant

### ISSUE THREAD

**Issue by xyyeah** [QianliM/cape_utils#6]
Hi, thanks for the exciting work to contribute the dataset. I found that the order of the points for the minimal shape and clothed shape is inconsistant, also, the order of the points from the smpl model which estimated from the minimal shape is different to the minimal shape. Can you please explain why they are not in the same order? Also, is there a conversion index between them that can be shared? Thank you very much!

![vertices_mc_align](https://user-images.githubusercontent.com/90754199/154053968-d3f2138d-09e0-4978-a76c-48c95d80122c.png)

**Comment by qianlim** [comment]
Hi, can you provide the filename of this example?

**Comment by xyyeah** [comment]
Thanks for your quick reply, i find the problem. I save the shape into the obj file and then reload the obj file, the order of the points are changed. Thanks and close.
